name = "ca_settings_subca"

[CA_KEY_SOURCE_HARDWARE_SETTINGS]
p11_settings_path = "../test_data/cert/configs/ecdsa_hardware/p11_settings.toml"
ca_key_id = "ecdsa_subca"
ca_cert_path = "../test_data/cert/data/ecdsa_hardware/cert_subca.pem"

[CRL_SETTINGS]
digest_algorithm = "sha256"
crl_validity = "24H"
crl_publishing_path = "../test_data/cert/data/ecdsa_hardware/crl_subca.pem"