name = "ca_settings_root"

[CA_KEY_SOURCE_SOFTWARE_SETTINGS]
ca_private_key_path = "../test_data/cert/data/ecdsa_software/private_key_root.pem"
ca_cert_path = "../test_data/cert/data/ecdsa_software/cert_root.pem"

[CRL_SETTINGS]
digest_algorithm = "sha256"
crl_validity = "1MO"
crl_publishing_path = "../test_data/cert/data/ecdsa_software/crl_root.pem"