name = "key_subca_rsa_software"

[ECDSA]
curve = "secp384r1"

[KEY_SOURCE_SOFTWARE]
private_key_out_path = "../test_data/cert/data/ecdsa_software/private_key_subca.pem"
public_key_out_path = "../test_data/cert/data/ecdsa_software/public_key_subca.pem"

[CSR]
csr_digest_algorithm = "sha256"
csr_out_path = "../test_data/cert/data/ecdsa_software/key_subca_csr.pem"

[CSR_SUBJECT_INFO]
organizationalUnit = "Go CA generated CSR"