[ADD_REVOCATION_ENTRIES]
entries = [
    {serial_number = "3e8",revocation_date = "2022-04-04 13:19:01",revocation_reason = "unspecified"},
    {serial_number = "3e9",revocation_date = "2022-04-04 13:19:01",revocation_reason = "unspecified"},
    {serial_number = "3ea",revocation_date = "2022-04-04 13:19:01",revocation_reason = "keyCompromise"}
]

[REMOVE_REVOCATION_ENTRIES]
entries = [
	"123", "456"
]