name = "ca_settings_subca_rsa_software"

[CA_KEY_SOURCE_SOFTWARE_SETTINGS]
ca_private_key_path = "../test_data/cert/data/rsa_software/private_key_subca.pem"
ca_cert_path = "../test_data/cert/data/rsa_software/cert_subca.pem"

[CRL_SETTINGS]
digest_algorithm = "sha256"
crl_validity = "24H"
crl_publishing_path = "../test_data/cert/data/rsa_software/crl_subca.pem"