name = "key_root_rsa_software"

[RSA]
key_length = 4096

[KEY_SOURCE_SOFTWARE]
private_key_out_path = "../test_data/cert/data/rsa_software/private_key_root.pem"
public_key_out_path = "../test_data/cert/data/rsa_software/public_key_root.pem"